### ISSUE TITLE
Flutter 2.0 and null-safety

### ISSUE THREAD

**Issue by ciamax** [snj07/flutter_show_more_text_popup#5]
Any chance of an upgrade to flutter 2.0 and null-safety support?

**Comment by benja8151** [comment]
You can use my fork: #4 , not sure why @snj07 closed that pull request.

**Comment by ciamax** [comment]
I have overridden the dependency to your repo and made some quick tests. All seems to work fine but it would be great to get the package from flutter pub.

Thank you.

**Comment by ufobm** [comment]
Same request from here! Thank you!

**Comment by snj07** [comment]
@benja8151 Sorry, I was busy with some stuff and there were some changes required in your PR so I didn't accept it.
@ciamax  @ufobm  null-safety changes are published. You can update the version to 0.3.0 to get it. Thanks!
